services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - ./storage:/verdaccio/storage
      - ./config:/verdaccio/conf
      - ./plugins:/verdaccio/plugins
      - ./logs:/verdaccio/logs
networks:
  node-network:
    driver: bridge
